//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""1ac296f0-3699-4609-a461-6b2b95c57fde"",
            ""actions"": [
                {
                    ""name"": ""TriggerPause"",
                    ""type"": ""Button"",
                    ""id"": ""773b9d6f-9119-4440-9a79-0646710cda53"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GeneratePopup"",
                    ""type"": ""Button"",
                    ""id"": ""04e53f8a-b4eb-4396-a276-58b202527225"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GenerateBanner"",
                    ""type"": ""Button"",
                    ""id"": ""5c79aaa1-cc34-4f74-a334-eddebd456fea"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveBaseCar"",
                    ""type"": ""Value"",
                    ""id"": ""b653ab16-d7e2-473c-bec5-22bd32feba64"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ConfirmMushroomControl"",
                    ""type"": ""Button"",
                    ""id"": ""a3398864-60f7-453c-9a99-6f7e760276ac"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ConfirmSnailControl"",
                    ""type"": ""Button"",
                    ""id"": ""faf136ca-e6e8-4f46-bceb-578886945def"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SnailLevelUpBegins"",
                    ""type"": ""Button"",
                    ""id"": ""7d0cf7bf-ca46-43f1-b804-282e0c08a7a7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LevelUpOption1"",
                    ""type"": ""Button"",
                    ""id"": ""1c75faf5-ee7b-44ff-8f16-c7a25dcf78ff"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LevelUpOption2"",
                    ""type"": ""Button"",
                    ""id"": ""4ba5b637-3350-429a-b71d-46fc99baefe3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Sprint"",
                    ""type"": ""Button"",
                    ""id"": ""fe2b3957-07b2-4ce4-841c-57ace975558a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""aef2fbdf-3713-421f-8bdf-2e48052ef9f9"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TriggerPause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""75e4c9a0-06e3-443f-b7c5-3fc5ec3878a2"",
                    ""path"": ""<Keyboard>/slash"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GeneratePopup"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""00215f9f-061d-49fb-a6b1-faf59a7e88d8"",
                    ""path"": ""<Keyboard>/period"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GenerateBanner"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""67e6a5e8-6452-49dc-87b1-c5987e2cca4a"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBaseCar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""06524afe-ac47-4564-bfc0-e292080f9bbf"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBaseCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""856801ba-c0a2-419b-8de3-1f2719faf768"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBaseCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""fb2b3877-4b17-49b7-a112-89d62baf8f4c"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBaseCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""5829541b-0e56-48b1-9645-a5a0b495bd13"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBaseCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ArrowKey"",
                    ""id"": ""5c0ef9ad-b70d-4798-bf89-ef4351d85c66"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBaseCar"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a6c41da2-14bb-4aba-b638-b03f9765b0ea"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBaseCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""985c2335-add7-4cf1-9d1d-55b7ed76a809"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBaseCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""12c752b7-87de-4a13-972b-923791048b76"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBaseCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ac18adbc-8813-4879-b94b-5795bfebda5b"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveBaseCar"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""867458b8-2976-4eb7-b464-d39a9110cead"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmMushroomControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81919f37-5acb-4639-9946-8a224f15e868"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ConfirmSnailControl"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""73abda64-97ab-4a65-a3fb-6cb432761553"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SnailLevelUpBegins"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5ada1d4c-8568-4c4e-b2bb-cbfa4b4c56b6"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LevelUpOption1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2029021c-4f84-4a16-9dd5-5995697e885e"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LevelUpOption2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dd0db869-f989-4b6f-9753-1de205ca25bf"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Sprint"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UI"",
            ""id"": ""daa719d3-417a-4773-9284-98b56b5e874f"",
            ""actions"": [
                {
                    ""name"": ""Navigate"",
                    ""type"": ""PassThrough"",
                    ""id"": ""87dd4905-816f-403e-84f0-44e7b3c6fe2a"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Submit"",
                    ""type"": ""Button"",
                    ""id"": ""a84d7c69-73d5-4893-8d2a-66dafc655b7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Cancel"",
                    ""type"": ""Button"",
                    ""id"": ""fd8f98a7-d353-4db7-9e0d-70d8bd9448ae"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Point"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0cbf84bb-9764-444d-9606-c97375ea7224"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Click"",
                    ""type"": ""PassThrough"",
                    ""id"": ""8bbe0671-3de0-4972-8c22-8e242399ba00"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ScrollWheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""82319d64-a590-4ed0-80dc-cb21b6d1d7b5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiddleClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""465b13b1-0001-42dd-9ceb-8952f8f2f2bf"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightClick"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2a73731b-d06b-45ea-abcc-873eb0911814"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SnailLevelUpBegins"",
                    ""type"": ""Button"",
                    ""id"": ""eaaead47-59c6-46de-be09-81a5cc061d52"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LevelUpOption1"",
                    ""type"": ""Button"",
                    ""id"": ""891ab554-fc61-4f40-8003-4ba9e2e3eec0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LevelUpOption2"",
                    ""type"": ""Button"",
                    ""id"": ""13c8f067-4ced-4fd3-8c9b-986497e9e6e7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""Keyboard"",
                    ""id"": ""ff527021-f211-4c02-933e-5976594c46ed"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""563fbfdd-0f09-408d-aa75-8642c4f08ef0"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""up"",
                    ""id"": ""eb480147-c587-4a33-85ed-eb0ab9942c43"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""2bf42165-60bc-42ca-8072-8c13ab40239b"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""85d264ad-e0a0-4565-b7ff-1a37edde51ac"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""74214943-c580-44e4-98eb-ad7eebe17902"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""cea9b045-a000-445b-95b8-0c171af70a3b"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""8607c725-d935-4808-84b1-8354e29bab63"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""4cda81dc-9edd-4e03-9d7c-a71a14345d0b"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9e92bb26-7e3b-4ec4-b06b-3c8f8e498ddc"",
                    ""path"": ""*/{Submit}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Submit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82627dcc-3b13-4ba9-841d-e4b746d6553e"",
                    ""path"": ""*/{Cancel}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Cancel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c52c8e0b-8179-41d3-b8a1-d149033bbe86"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1394cbc-336e-44ce-9ea8-6007ed6193f7"",
                    ""path"": ""<Pen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Keyboard&Mouse"",
                    ""action"": ""Point"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4faf7dc9-b979-4210-aa8c-e808e1ef89f5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d66d5ba-88d7-48e6-b1cd-198bbfef7ace"",
                    ""path"": ""<Pen>/tip"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""Click"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38c99815-14ea-4617-8627-164d27641299"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""ScrollWheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""24066f69-da47-44f3-a07e-0015fb02eb2e"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""MiddleClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4c191405-5738-4d4b-a523-c6a301dbf754"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": "";Keyboard&Mouse"",
                    ""action"": ""RightClick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Keyboard&Mouse"",
            ""bindingGroup"": ""Keyboard&Mouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_TriggerPause = m_Player.FindAction("TriggerPause", throwIfNotFound: true);
        m_Player_GeneratePopup = m_Player.FindAction("GeneratePopup", throwIfNotFound: true);
        m_Player_GenerateBanner = m_Player.FindAction("GenerateBanner", throwIfNotFound: true);
        m_Player_MoveBaseCar = m_Player.FindAction("MoveBaseCar", throwIfNotFound: true);
        m_Player_ConfirmMushroomControl = m_Player.FindAction("ConfirmMushroomControl", throwIfNotFound: true);
        m_Player_ConfirmSnailControl = m_Player.FindAction("ConfirmSnailControl", throwIfNotFound: true);
        m_Player_SnailLevelUpBegins = m_Player.FindAction("SnailLevelUpBegins", throwIfNotFound: true);
        m_Player_LevelUpOption1 = m_Player.FindAction("LevelUpOption1", throwIfNotFound: true);
        m_Player_LevelUpOption2 = m_Player.FindAction("LevelUpOption2", throwIfNotFound: true);
        m_Player_Sprint = m_Player.FindAction("Sprint", throwIfNotFound: true);
        // UI
        m_UI = asset.FindActionMap("UI", throwIfNotFound: true);
        m_UI_Navigate = m_UI.FindAction("Navigate", throwIfNotFound: true);
        m_UI_Submit = m_UI.FindAction("Submit", throwIfNotFound: true);
        m_UI_Cancel = m_UI.FindAction("Cancel", throwIfNotFound: true);
        m_UI_Point = m_UI.FindAction("Point", throwIfNotFound: true);
        m_UI_Click = m_UI.FindAction("Click", throwIfNotFound: true);
        m_UI_ScrollWheel = m_UI.FindAction("ScrollWheel", throwIfNotFound: true);
        m_UI_MiddleClick = m_UI.FindAction("MiddleClick", throwIfNotFound: true);
        m_UI_RightClick = m_UI.FindAction("RightClick", throwIfNotFound: true);
        m_UI_SnailLevelUpBegins = m_UI.FindAction("SnailLevelUpBegins", throwIfNotFound: true);
        m_UI_LevelUpOption1 = m_UI.FindAction("LevelUpOption1", throwIfNotFound: true);
        m_UI_LevelUpOption2 = m_UI.FindAction("LevelUpOption2", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_TriggerPause;
    private readonly InputAction m_Player_GeneratePopup;
    private readonly InputAction m_Player_GenerateBanner;
    private readonly InputAction m_Player_MoveBaseCar;
    private readonly InputAction m_Player_ConfirmMushroomControl;
    private readonly InputAction m_Player_ConfirmSnailControl;
    private readonly InputAction m_Player_SnailLevelUpBegins;
    private readonly InputAction m_Player_LevelUpOption1;
    private readonly InputAction m_Player_LevelUpOption2;
    private readonly InputAction m_Player_Sprint;
    public struct PlayerActions
    {
        private @Controls m_Wrapper;
        public PlayerActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @TriggerPause => m_Wrapper.m_Player_TriggerPause;
        public InputAction @GeneratePopup => m_Wrapper.m_Player_GeneratePopup;
        public InputAction @GenerateBanner => m_Wrapper.m_Player_GenerateBanner;
        public InputAction @MoveBaseCar => m_Wrapper.m_Player_MoveBaseCar;
        public InputAction @ConfirmMushroomControl => m_Wrapper.m_Player_ConfirmMushroomControl;
        public InputAction @ConfirmSnailControl => m_Wrapper.m_Player_ConfirmSnailControl;
        public InputAction @SnailLevelUpBegins => m_Wrapper.m_Player_SnailLevelUpBegins;
        public InputAction @LevelUpOption1 => m_Wrapper.m_Player_LevelUpOption1;
        public InputAction @LevelUpOption2 => m_Wrapper.m_Player_LevelUpOption2;
        public InputAction @Sprint => m_Wrapper.m_Player_Sprint;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @TriggerPause.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTriggerPause;
                @TriggerPause.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTriggerPause;
                @TriggerPause.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnTriggerPause;
                @GeneratePopup.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGeneratePopup;
                @GeneratePopup.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGeneratePopup;
                @GeneratePopup.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGeneratePopup;
                @GenerateBanner.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGenerateBanner;
                @GenerateBanner.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGenerateBanner;
                @GenerateBanner.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGenerateBanner;
                @MoveBaseCar.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveBaseCar;
                @MoveBaseCar.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveBaseCar;
                @MoveBaseCar.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMoveBaseCar;
                @ConfirmMushroomControl.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnConfirmMushroomControl;
                @ConfirmMushroomControl.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnConfirmMushroomControl;
                @ConfirmMushroomControl.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnConfirmMushroomControl;
                @ConfirmSnailControl.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnConfirmSnailControl;
                @ConfirmSnailControl.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnConfirmSnailControl;
                @ConfirmSnailControl.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnConfirmSnailControl;
                @SnailLevelUpBegins.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSnailLevelUpBegins;
                @SnailLevelUpBegins.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSnailLevelUpBegins;
                @SnailLevelUpBegins.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSnailLevelUpBegins;
                @LevelUpOption1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLevelUpOption1;
                @LevelUpOption1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLevelUpOption1;
                @LevelUpOption1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLevelUpOption1;
                @LevelUpOption2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLevelUpOption2;
                @LevelUpOption2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLevelUpOption2;
                @LevelUpOption2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnLevelUpOption2;
                @Sprint.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
                @Sprint.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnSprint;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TriggerPause.started += instance.OnTriggerPause;
                @TriggerPause.performed += instance.OnTriggerPause;
                @TriggerPause.canceled += instance.OnTriggerPause;
                @GeneratePopup.started += instance.OnGeneratePopup;
                @GeneratePopup.performed += instance.OnGeneratePopup;
                @GeneratePopup.canceled += instance.OnGeneratePopup;
                @GenerateBanner.started += instance.OnGenerateBanner;
                @GenerateBanner.performed += instance.OnGenerateBanner;
                @GenerateBanner.canceled += instance.OnGenerateBanner;
                @MoveBaseCar.started += instance.OnMoveBaseCar;
                @MoveBaseCar.performed += instance.OnMoveBaseCar;
                @MoveBaseCar.canceled += instance.OnMoveBaseCar;
                @ConfirmMushroomControl.started += instance.OnConfirmMushroomControl;
                @ConfirmMushroomControl.performed += instance.OnConfirmMushroomControl;
                @ConfirmMushroomControl.canceled += instance.OnConfirmMushroomControl;
                @ConfirmSnailControl.started += instance.OnConfirmSnailControl;
                @ConfirmSnailControl.performed += instance.OnConfirmSnailControl;
                @ConfirmSnailControl.canceled += instance.OnConfirmSnailControl;
                @SnailLevelUpBegins.started += instance.OnSnailLevelUpBegins;
                @SnailLevelUpBegins.performed += instance.OnSnailLevelUpBegins;
                @SnailLevelUpBegins.canceled += instance.OnSnailLevelUpBegins;
                @LevelUpOption1.started += instance.OnLevelUpOption1;
                @LevelUpOption1.performed += instance.OnLevelUpOption1;
                @LevelUpOption1.canceled += instance.OnLevelUpOption1;
                @LevelUpOption2.started += instance.OnLevelUpOption2;
                @LevelUpOption2.performed += instance.OnLevelUpOption2;
                @LevelUpOption2.canceled += instance.OnLevelUpOption2;
                @Sprint.started += instance.OnSprint;
                @Sprint.performed += instance.OnSprint;
                @Sprint.canceled += instance.OnSprint;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);

    // UI
    private readonly InputActionMap m_UI;
    private IUIActions m_UIActionsCallbackInterface;
    private readonly InputAction m_UI_Navigate;
    private readonly InputAction m_UI_Submit;
    private readonly InputAction m_UI_Cancel;
    private readonly InputAction m_UI_Point;
    private readonly InputAction m_UI_Click;
    private readonly InputAction m_UI_ScrollWheel;
    private readonly InputAction m_UI_MiddleClick;
    private readonly InputAction m_UI_RightClick;
    private readonly InputAction m_UI_SnailLevelUpBegins;
    private readonly InputAction m_UI_LevelUpOption1;
    private readonly InputAction m_UI_LevelUpOption2;
    public struct UIActions
    {
        private @Controls m_Wrapper;
        public UIActions(@Controls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Navigate => m_Wrapper.m_UI_Navigate;
        public InputAction @Submit => m_Wrapper.m_UI_Submit;
        public InputAction @Cancel => m_Wrapper.m_UI_Cancel;
        public InputAction @Point => m_Wrapper.m_UI_Point;
        public InputAction @Click => m_Wrapper.m_UI_Click;
        public InputAction @ScrollWheel => m_Wrapper.m_UI_ScrollWheel;
        public InputAction @MiddleClick => m_Wrapper.m_UI_MiddleClick;
        public InputAction @RightClick => m_Wrapper.m_UI_RightClick;
        public InputAction @SnailLevelUpBegins => m_Wrapper.m_UI_SnailLevelUpBegins;
        public InputAction @LevelUpOption1 => m_Wrapper.m_UI_LevelUpOption1;
        public InputAction @LevelUpOption2 => m_Wrapper.m_UI_LevelUpOption2;
        public InputActionMap Get() { return m_Wrapper.m_UI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActions set) { return set.Get(); }
        public void SetCallbacks(IUIActions instance)
        {
            if (m_Wrapper.m_UIActionsCallbackInterface != null)
            {
                @Navigate.started -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Navigate.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnNavigate;
                @Submit.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Submit.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSubmit;
                @Cancel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Cancel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Cancel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnCancel;
                @Point.started -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Point.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnPoint;
                @Click.started -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @Click.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnClick;
                @ScrollWheel.started -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @ScrollWheel.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnScrollWheel;
                @MiddleClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @MiddleClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnMiddleClick;
                @RightClick.started -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @RightClick.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnRightClick;
                @SnailLevelUpBegins.started -= m_Wrapper.m_UIActionsCallbackInterface.OnSnailLevelUpBegins;
                @SnailLevelUpBegins.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnSnailLevelUpBegins;
                @SnailLevelUpBegins.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnSnailLevelUpBegins;
                @LevelUpOption1.started -= m_Wrapper.m_UIActionsCallbackInterface.OnLevelUpOption1;
                @LevelUpOption1.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnLevelUpOption1;
                @LevelUpOption1.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnLevelUpOption1;
                @LevelUpOption2.started -= m_Wrapper.m_UIActionsCallbackInterface.OnLevelUpOption2;
                @LevelUpOption2.performed -= m_Wrapper.m_UIActionsCallbackInterface.OnLevelUpOption2;
                @LevelUpOption2.canceled -= m_Wrapper.m_UIActionsCallbackInterface.OnLevelUpOption2;
            }
            m_Wrapper.m_UIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Navigate.started += instance.OnNavigate;
                @Navigate.performed += instance.OnNavigate;
                @Navigate.canceled += instance.OnNavigate;
                @Submit.started += instance.OnSubmit;
                @Submit.performed += instance.OnSubmit;
                @Submit.canceled += instance.OnSubmit;
                @Cancel.started += instance.OnCancel;
                @Cancel.performed += instance.OnCancel;
                @Cancel.canceled += instance.OnCancel;
                @Point.started += instance.OnPoint;
                @Point.performed += instance.OnPoint;
                @Point.canceled += instance.OnPoint;
                @Click.started += instance.OnClick;
                @Click.performed += instance.OnClick;
                @Click.canceled += instance.OnClick;
                @ScrollWheel.started += instance.OnScrollWheel;
                @ScrollWheel.performed += instance.OnScrollWheel;
                @ScrollWheel.canceled += instance.OnScrollWheel;
                @MiddleClick.started += instance.OnMiddleClick;
                @MiddleClick.performed += instance.OnMiddleClick;
                @MiddleClick.canceled += instance.OnMiddleClick;
                @RightClick.started += instance.OnRightClick;
                @RightClick.performed += instance.OnRightClick;
                @RightClick.canceled += instance.OnRightClick;
                @SnailLevelUpBegins.started += instance.OnSnailLevelUpBegins;
                @SnailLevelUpBegins.performed += instance.OnSnailLevelUpBegins;
                @SnailLevelUpBegins.canceled += instance.OnSnailLevelUpBegins;
                @LevelUpOption1.started += instance.OnLevelUpOption1;
                @LevelUpOption1.performed += instance.OnLevelUpOption1;
                @LevelUpOption1.canceled += instance.OnLevelUpOption1;
                @LevelUpOption2.started += instance.OnLevelUpOption2;
                @LevelUpOption2.performed += instance.OnLevelUpOption2;
                @LevelUpOption2.canceled += instance.OnLevelUpOption2;
            }
        }
    }
    public UIActions @UI => new UIActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("Keyboard&Mouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnTriggerPause(InputAction.CallbackContext context);
        void OnGeneratePopup(InputAction.CallbackContext context);
        void OnGenerateBanner(InputAction.CallbackContext context);
        void OnMoveBaseCar(InputAction.CallbackContext context);
        void OnConfirmMushroomControl(InputAction.CallbackContext context);
        void OnConfirmSnailControl(InputAction.CallbackContext context);
        void OnSnailLevelUpBegins(InputAction.CallbackContext context);
        void OnLevelUpOption1(InputAction.CallbackContext context);
        void OnLevelUpOption2(InputAction.CallbackContext context);
        void OnSprint(InputAction.CallbackContext context);
    }
    public interface IUIActions
    {
        void OnNavigate(InputAction.CallbackContext context);
        void OnSubmit(InputAction.CallbackContext context);
        void OnCancel(InputAction.CallbackContext context);
        void OnPoint(InputAction.CallbackContext context);
        void OnClick(InputAction.CallbackContext context);
        void OnScrollWheel(InputAction.CallbackContext context);
        void OnMiddleClick(InputAction.CallbackContext context);
        void OnRightClick(InputAction.CallbackContext context);
        void OnSnailLevelUpBegins(InputAction.CallbackContext context);
        void OnLevelUpOption1(InputAction.CallbackContext context);
        void OnLevelUpOption2(InputAction.CallbackContext context);
    }
}
